
apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-deployment
  namespace: lab16-sehs
  labels:
    app: backend-deployment
spec:
  selector:
    matchLabels:
      app: backend
  replicas: 1
  template:
    metadata:
      labels:
        app: backend
    spec:
      volumes:
      - name: db-password
        secret:
          secretName: db-secret
      - name: pre-install
        emptyDir: {}
    #  initContainers:
    #   - name: pre-install
    #     image: busybox
    #     securityContext:
    #       runAsUser: 0
    #       allowPrivilegeEscalation: false
    #     command: ['sh', '-c', 'cat /db-secret/db-password >> /run/secrets/db-password']
    #     volumeMounts:
    #     - name: db-password
    #       mountPath: "/db-secret"
    #     - name: pre-install
    #       mountPath: "/run/secrets"
      containers:
      - name: backend
        image: 3booda24/app-go:latest
        imagePullPolicy: Always
        securityContext:
          runAsUser: 0
        ports:
        - containerPort: 8000
        volumeMounts:
        - name: db-password
          mountPath: /run/secrets/db-password
          subPath: db-password
          readOnly: true
        # - name: db-password
        #   mountPath: "/db-secret"
